GET http://localhost:3000/users/

###

POST http://localhost:3000/users

Content-Type: application/json/html


{
  "data": {"name": "Test User",
  "about": "Info User",
  "avatar": "http://www.westend-dentist.ca/wp-content/uploads/2014/01/testimonial-img-man.png"}
}
